### ISSUE TITLE
"chown failed" on manala.files : attributes > File

### ISSUE THREAD

**Issue by Tom32i** [manala/ansible-role-files#2]
I'm just trying to create a directory and a generated config file inside it.
But the file task always make the provision fail.

Here's my Ansible configuration:
```
  #########
  # Files #
  #########

  files_attributes:
    - path: "{{ app.dir }}/catalog"
      state: "directory"
    - path: "{{ app.dir }}/catalog/playlists.json"
      template: "{{ playbook_dir }}/templates/app_list/app/playlists.json.j2"
```

Here's the full error output for `chown failed`:
```
TASK [manala.files : attributes > File] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0755", "msg": "chown failed", "owner": "501", "path": "/srv/app/catalog", "size": 68, "state": "directory", "uid": 501}
```

Event though the provision fails, the directory `catalog` has been successfully created.
_(If I comment the `catalog` directory instruction, I get the same error on the JSON file when provisioning. The JSON file is successfully created as well, despite the provision fails.)_

I'm using __Vagrant 1.8.4__ and __Ansible 1.9.6__.
If I comment the whole `files_attributes` section, the provision runs successfully!
